variable "kubeconfig_path" {
  description = "Path to the Talos cluster's kubeconfig, generated by the proxmox-tofu / talosctl bootstrap."
  type        = string
  default     = "../proxmox-tofu/_out/kubeconfig"
}

variable "ingress_nginx_namespace" {
  description = "Namespace to install the ingress-nginx controller into."
  type        = string
  default     = "ingress-nginx"
}

variable "ingress_nginx_chart_version" {
  description = "Version of the ingress-nginx Helm chart to install."
  type        = string
  default     = "4.15.1"
}

variable "headlamp_namespace" {
  description = "Namespace to install Headlamp into."
  type        = string
  default     = "headlamp"
}

variable "headlamp_chart_version" {
  description = "Version of the Headlamp Helm chart to install."
  type        = string
  default     = "0.44.0"
}

variable "headlamp_hostname" {
  description = "Hostname the Headlamp UI will be served on via Ingress. Add this to your workstation's /etc/hosts pointing at a worker node IP (no in-cluster LoadBalancer/DNS is set up)."
  type        = string
  default     = "headlamp.talos.lab"
}

variable "csi_driver_nfs_namespace" {
  description = "Namespace to install csi-driver-nfs into."
  type        = string
  default     = "csi-driver-nfs"
}

variable "csi_driver_nfs_chart_version" {
  description = "Version of the csi-driver-nfs Helm chart to install."
  type        = string
  default     = "v4.9.0"
}

variable "nfs_servers" {
  description = "NFS servers provisioned in proxmox-tofu, each backing its own StorageClass (keyed by StorageClass name). Exactly one must be marked default."
  type = map(object({
    address     = string
    export_path = string
    default     = bool
  }))
  default = {
    "nfs-csi" = {
      address     = "192.168.0.148" # nfs-storage-pve2
      export_path = "/srv/nfs/data"
      default     = true
    }
    "nfs-csi-pve3" = {
      address     = "192.168.0.215" # nfs-storage-pve3
      export_path = "/srv/nfs/data"
      default     = false
    }
  }
}

variable "authentik_hostname" {
  description = "Authentik's Ingress hostname, as configured in cluster-auth (needed here so CoreDNS can resolve it in-cluster too — see coredns.tf)."
  type        = string
  default     = "auth.talos.lab"
}

variable "nexus_namespace" {
  description = "Namespace to install Nexus Repository Manager into."
  type        = string
  default     = "nexus"
}

variable "nexus_chart_version" {
  description = "Version of the sonatype/nexus-repository-manager Helm chart to install."
  type        = string
  default     = "64.2.0"
}

variable "nexus_hostname" {
  description = "Hostname the Nexus web UI will be served on via Ingress."
  type        = string
  default     = "nexus.talos.lab"
}

variable "nexus_docker_hostname" {
  description = "Hostname for Nexus's docker-hosted repo connector, used as the image registry host by every app's Helm chart (e.g. clusterkeep-ui's image.repository)."
  type        = string
  default     = "registry.talos.lab"
}

variable "nexus_docker_port" {
  description = "Port Nexus's docker-hosted repo connector listens on. Must match the HTTP port configured on the \"docker (hosted)\" repository created in the Nexus UI after first install (see README) — the chart only opens the port, it doesn't create the repository."
  type        = number
  default     = 5000
}

variable "nexus_storage_size" {
  description = "Size of the PVC (backed by the nfs-csi default StorageClass) Nexus stores blobs/metadata on."
  type        = string
  default     = "20Gi"
}

variable "cloudflare_tunnel_chart_version" {
  description = "Version of the cloudflare/cloudflare-tunnel Helm chart to install."
  type        = string
  default     = "0.3.2"
}

variable "cloudflare_account_id" {
  description = "Cloudflare account ID, from the right sidebar of any domain's Overview page in the dashboard."
  type        = string
}

variable "cloudflare_tunnel_name" {
  description = "Name given to the tunnel via `cloudflared tunnel create <name>`."
  type        = string
  default     = "clusterkeep"
}

variable "cloudflare_tunnel_id" {
  description = "Tunnel ID printed by `cloudflared tunnel create` (also the filename, minus .json, under ~/.cloudflared)."
  type        = string
}

variable "cloudflare_tunnel_credentials_path" {
  description = "Path to the credentials JSON file written by `cloudflared tunnel create`, e.g. ~/.cloudflared/<tunnel-id>.json. Never committed — only referenced from here."
  type        = string
}

variable "cloudflare_tunnel_hostname" {
  description = "Public hostname routed through the tunnel to clusterkeep-ui."
  type        = string
  default     = "login.clusterkeep.com"
}
