variable "kubeconfig_path" {
  description = "Path to the Talos cluster's kubeconfig, generated by the proxmox-tofu / talosctl bootstrap."
  type        = string
  default     = "../proxmox-tofu/_out/kubeconfig"
}

variable "ingress_nginx_namespace" {
  description = "Namespace to install the ingress-nginx controller into."
  type        = string
  default     = "ingress-nginx"
}

variable "ingress_nginx_chart_version" {
  description = "Version of the ingress-nginx Helm chart to install."
  type        = string
  default     = "4.15.1"
}

variable "headlamp_namespace" {
  description = "Namespace to install Headlamp into."
  type        = string
  default     = "headlamp"
}

variable "headlamp_chart_version" {
  description = "Version of the Headlamp Helm chart to install."
  type        = string
  default     = "0.44.0"
}

variable "headlamp_hostname" {
  description = "Hostname the Headlamp UI will be served on via Ingress. Add this to your workstation's /etc/hosts pointing at a worker node IP (no in-cluster LoadBalancer/DNS is set up)."
  type        = string
  default     = "headlamp.talos.lab"
}

variable "csi_driver_nfs_namespace" {
  description = "Namespace to install csi-driver-nfs into."
  type        = string
  default     = "csi-driver-nfs"
}

variable "csi_driver_nfs_chart_version" {
  description = "Version of the csi-driver-nfs Helm chart to install."
  type        = string
  default     = "v4.9.0"
}

variable "nfs_server_address" {
  description = "IP/hostname of the nfs-storage VM provisioned in proxmox-tofu."
  type        = string
  default     = "192.168.0.28"
}

variable "nfs_export_path" {
  description = "Path exported by the nfs-storage VM (see proxmox-tofu/scripts/setup-nfs-server.sh)."
  type        = string
  default     = "/srv/nfs/data"
}

variable "authentik_hostname" {
  description = "Authentik's Ingress hostname, as configured in cluster-auth (needed here so CoreDNS can resolve it in-cluster too — see coredns.tf)."
  type        = string
  default     = "auth.talos.lab"
}

variable "nexus_namespace" {
  description = "Namespace to install Nexus Repository Manager into."
  type        = string
  default     = "nexus"
}

variable "nexus_chart_version" {
  description = "Version of the sonatype/nexus-repository-manager Helm chart to install."
  type        = string
  default     = "64.2.0"
}

variable "nexus_hostname" {
  description = "Hostname the Nexus web UI will be served on via Ingress."
  type        = string
  default     = "nexus.talos.lab"
}

variable "nexus_docker_hostname" {
  description = "Hostname for Nexus's docker-hosted repo connector, used as the image registry host by every app's Helm chart (e.g. kubestore-ui's image.repository)."
  type        = string
  default     = "registry.talos.lab"
}

variable "nexus_docker_port" {
  description = "Port Nexus's docker-hosted repo connector listens on. Must match the HTTP port configured on the \"docker (hosted)\" repository created in the Nexus UI after first install (see README) — the chart only opens the port, it doesn't create the repository."
  type        = number
  default     = 5000
}

variable "nexus_storage_size" {
  description = "Size of the PVC (backed by the nfs-csi default StorageClass) Nexus stores blobs/metadata on."
  type        = string
  default     = "20Gi"
}
