name: plan

on:
  push:
    tags: ["v*.*.*"]

jobs:
  plan:
    runs-on: [self-hosted]
    steps:
      - name: Sync all repos
        run: sync-repos.sh

      - name: tofu plan
        run: cluster-cli tofu cluster-config --tag "${{ github.ref_name }}" plan
